openapi: 3.1.0
info:
  title: NoTaker API
  version: 1.0.0
  description: API documentation for the NoTaker application.

servers:
  - url: http://localhost:3000
    description: Local Development Server
  - url: https://notakers-api.onrender.com
    description: Production server on render

components:
  $ref: './components.yaml'

security:
  - bearerAuth: []

paths:
  $ref: './paths.yaml'
